spring.application.name=Restaurant

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8081}

server.servlet.session.persistent=true

logging.level.root = info
logging.level.org.springframework.web = info
logging.level.nbcc = debug
logging.file.name=logs/app-rest-api.log

jwt.issuer=NBCC
# 345600 seconds = 4 days and will expire after presentation, and we set it to 3600 again
jwt.timeout=345600

# Key locations
jwt.private-key-location=classpath:keys/private_key.pem
jwt.public-key-location=classpath:keys/public_key.pem

# Email configuration
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=proj_resto
spring.mail.password=proj_resto
spring.mail.properties.mail.smtp.auth=false
email.from=noreply@canada.ca

#spring.thymeleaf.cache=false